template_categories:
  - name: "Bug Reports"
    description: "Report issues related to bugs in the project."
    templates:
      - bug_report.md
      - crash_report.md

  - name: "Feature Requests"
    description: "Suggest new features or improvements for the project."
    templates:
      - feature_request.md
      - ui_ux_request.md

  - name: "Questions"
    description: "Ask questions or seek clarification."
    templates:
      - general_question.md
      - documentation_question.md
